# Generated by Django 5.0.4 on 2024-05-01 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 1), null=True),
        ),
    ]
